name: Create Tag

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        strategy: regex # Optional since regex_pattern is defined
        root: "../../version"
        regex_pattern: "version=([0-9\\.])"
