name: Create Tag

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        strategy: regex
        root: ".github/version"
        regex_pattern: "version=(.*)"
        tag_message: "Changelog: Please check the latest changelog in [CHANGE-LOG-2020.md](https://github.com/tikivn/TKListing/blob/master/CHANGE-LOG-2020.md)"
